name: hi
description: Video chat
publish_to: 'none'
version: 4.5.2+75

environment:
  sdk: ">=2.19.4 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  flutter_launcher_icons: ^0.13.0
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0
  cloud_firestore: ^4.5.1
  flutter_webrtc: ^0.9.25
  shared_preferences: ^2.1.0
  sqflite: ^2.2.6
  path: ^1.8.2
  firebase_auth: ^4.4.1
  flutter_signin_button: ^2.0.0
  google_sign_in: ^6.1.0
  firebase_dynamic_links: ^5.1.0
  url_launcher: ^6.1.10

flutter_icons:
  image_path: "icon/hi.png"
  android: true
  ios: true
  remove_alpha_ios: true
  image_path_ios: "icon/ios/hi.png"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
# The following section is specific to Flutter.
flutter:
  generate: true
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - assets/local.properties
    - assets/icon/google.png
    - assets/icon/ad.png
