name: hi
description: Video chat
publish_to: 'none'
version: 1.3.42+46

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
#  dev_tok_rtc:
#    path: ../../local_plugins/dev_tok_rtc
  cupertino_icons: ^1.0.4
  flutter_launcher_icons: ^0.9.2
  wakelock: ^0.6.1+2
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0
  device_info: ^2.0.3
  permission_handler: ^9.2.0
  firebase_crashlytics: ^2.6.1
  connectivity: ^3.0.6
  package_info: ^2.0.2
  camera: ^0.9.4+19
  flutter_webrtc: ^0.8.5

flutter_icons:
  image_path: "icon/hi.png"
  android: true
  ios: true
  remove_alpha_ios: true
  image_path_ios: "icon/ios/hi.png"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
# The following section is specific to Flutter.
flutter:
  generate: true
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - assets/local.properties
  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
