name: hi
description: Video chat
publish_to: 'none'
version: 4.1.0+68

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  #  dev_tok_rtc:
  #    path: ../../local_plugins/dev_tok_rtc
  cupertino_icons: ^1.0.5
  flutter_launcher_icons: ^0.11.0
  wakelock: ^0.6.1+2
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0
  cloud_firestore: ^4.3.1
  flutter_webrtc: ^0.9.18
  shared_preferences: ^2.0.15
  sqflite: ^2.2.2
  path: ^1.8.1
  firebase_auth: ^4.2.4
  flutter_signin_button: ^2.0.0
  google_sign_in: ^5.4.2
  firebase_dynamic_links: ^5.0.11

flutter_icons:
  image_path: "icon/hi.png"
  android: true
  ios: true
  remove_alpha_ios: true
  image_path_ios: "icon/ios/hi.png"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
# The following section is specific to Flutter.
flutter:
  generate: true
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - assets/local.properties
    - assets/icon/google.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
